<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="src\DicomRouter.Core\DicomRouter.Core.csproj" />
    <None Include="src\DicomRouter.Infrastructure\DicomRouter.Infrastructure.csproj" />
    <None Include="src\DicomRouter.Service\DicomRouter.Service.csproj" />
    <None Include="src\DicomRouter.UI\DicomRouter.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="src\DicomRouter.UI\App.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="src\DicomRouter.UI\MainWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>

</Project>
